# Generated by Django 4.1.6 on 2023-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_merchandise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='merchandise',
            new_name='order_to_return',
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
